// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prciwmjozeneshcypkvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByY2l3bWpvemVuZXNoY3lwa3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4NTcxODIsImV4cCI6MjEwMzQzMzE4Mn0.jL87_3HF1cx1e2ojoHCXojOPSWWbyvbQIwvd50u0igU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});